# Generated by Django 5.0.6 on 2024-06-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='countered_hero',
        ),
        migrations.AddField(
            model_name='counter',
            name='countered_hero',
            field=models.ManyToManyField(related_name='countered_by', to='heros.hero'),
        ),
    ]
